lr: 0.001
batch_size: 128
drop_prob: 0.0
num_epochs: 350
gnn_name: 'GINEM'
model_name: 'N2GNN+'
num_hops: 3
hidden_channels: 120
num_layers: 6
JK: 'last'
pooling_method: "mean"
patience: 5
factor: 0.9
add_rd: True